repos:
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: "v5.10.1"
    hooks:
      - id: isort
  - repo: https://github.com/psf/black
    rev: "24.10.0"
    hooks:
      - id: black
        exclude: ^migrations/
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v5.0.0"
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: debug-statements
      - id: trailing-whitespace
        args: [ --markdown-linebreak-ext=md ]
      - id: check-merge-conflict
      - id: check-ast
      - id: check-byte-order-marker
      - id: check-json
      - id: check-symlinks
      - id: check-vcs-permalinks
      - id: check-xml
      - id: detect-aws-credentials
        args: [ '--allow-missing-credentials' ]
      - id: detect-private-key
      - id: forbid-new-submodules
      - id: end-of-file-fixer
  - repo: https://github.com/asottile/seed-isort-config
    rev: "v2.2.0"
    hooks:
      - id: seed-isort-config
